const mongoose = require('mongoose');
const { Schema } = mongoose;

const CVScheme = new Schema({
    User:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'user'
    },
    Template:{
        type:String,
        required:true
    },
    FirstName:{
        type:String,
        required:true
    },
    LastName:{
        type:String,
        required:true
    },
    image:{
        type:String,
        required:true
    },
    Email:{
        type:String,
        required:true
    },
    Mobile:{
        type:Number,
        required:true
    },
    Address1:{
        type:String,
        required:true
    },
    Address2:{
        type:String
    },
    City:{
        type:String,
        required:true
    },
    State:{
        type:String,
        required:true
    },
    Pincode:{
        type:String,
        required:true
    },
    Objective:{
        type:String,
        required:true
    },
    WorkExperience:[
        {
            JobTitle:{
                type:String,
                required:true
            },
            Organization:{
                type:String,
                required:true
            },
            StartYear:{
                type:Number,
                required:true
            },
            EndYear:{
                type:Number,
                required:true
            },
            Description:{
                type:String,
            }
        }
    ],
    EducationDetail:[
        {
            Type:{
                type:String,
                required:true
            },
            University:{
                type:String,
                required:true
            },
            Degree:{
                type:String,
                required:true
            },
            StartYear:{
                type:Number,
                required:true
            },
            EndYear:{
                type:Number,
                required:true
            }
        }
    ],
    Skills:[
        {
            Skill:{
                type:String,
                required:true
            }
        }
    ]
})

module.exports = mongoose.model("CVData",CVScheme)